#!/usr/bin/env node
/**
 * Generate version.ts from package.json
 * 
 * This script is run before build to inject the version at build time,
 * avoiding runtime file system access which may fail in bundled environments.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageJsonPath = join(__dirname, '..', 'package.json');
const outputPath = join(__dirname, '..', 'src', 'generated', 'version.ts');

// Read version from package.json
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
const version = packageJson.version || 'unknown';

// Ensure output directory exists
mkdirSync(dirname(outputPath), { recursive: true });

// Generate the version file
const versionContent = [
  '/**',
  ' * Auto-generated version file - DO NOT EDIT',
  ' * ',
  ' * Generated by scripts/generate-version.js from package.json',
  ' * This file is regenerated on every build.',
  ' */',
  '',
  'export const VERSION = "' + version + '";',
  ''
].join('\n');

writeFileSync(outputPath, versionContent);
console.log('Generated src/generated/version.ts with VERSION = "' + version + '"');
